### ISSUE TITLE
Not able to pre process the dataset 04 LiTS

### ISSUE THREAD

**Issue by aaekay** [ljwztc/CLIP-Driven-Universal-Model#40]
python -W ignore label_transfer.py
train len 131
Traceback (most recent call last):
  File "label_transfer.py", line 290, in <module>
    for index, batch in enumerate(train_loader):
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/transforms/io/dictionary.py", line 131, in __call__
    data = self._loader(d[key], reader)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/transforms/io/array.py", line 213, in __call__
    img = reader.read(filename)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/data/image_reader.py", line 421, in read
    img = nib.load(name, **kwargs_)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/nibabel/loadsave.py", line 115, in load
    raise ImageFileError(msg)
nibabel.filebasedimages.ImageFileError: File /home/amit_g/scr/datasets/clip/04_LiTS/label/liver_0.nii.gz is not a gzip file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/transforms/transform.py", line 89, in apply_transform
    return _apply_transform(transform, data, unpack_items)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/transforms/transform.py", line 53, in _apply_transform
    return transform(parameters)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/transforms/compose.py", line 173, in __call__
    input_ = apply_transform(_transform, input_, self.map_items, self.unpack_items, self.log_stats)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.io.dictionary.LoadImaged object at 0x7fdab8d054f0>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/data/dataset.py", line 97, in __getitem__
    return self._transform(index)
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/data/dataset.py", line 83, in _transform
    return apply_transform(self.transform, data_i) if self.transform is not None else data_i
  File "/home/amit_g/scratch/env/clip/lib/python3.8/site-packages/monai/transforms/transform.py", line 113, in apply_transform
    raise RuntimeError(f"applying transform {transform}") from e
RuntimeError: applying transform <monai.transforms.compose.Compose object at 0x7fdab746bfd0>

**Comment by ljwztc** [comment]
`File /home/amit_g/scr/datasets/clip/04_LiTS/label/liver_0.nii.gz is not a gzip file`
Please check you email or check the nib version

**Comment by aaekay** [comment]
which nibabel version is required? not mentioned in the requirements

**Comment by ljwztc** [comment]
the nibabel is included in monai. you can install through `pip install 'monai[all]'`
